### ISSUE TITLE
Package not available on Atmosphere

### ISSUE THREAD

**Issue by tophsic** [aramk/meteor-google-maps-marker-label#1]
Hi,

This morning, I am really surprised to have this message when I launch my meteor application:

``` bash
=> Errors prevented startup:                  

   While selecting package versions:
   error: unknown package in top-level dependencies: aramk:google-maps-marker-label
```

And I do not find aramk:google-maps-marker-label on https://atmospherejs.com.

Do you think it is normal ?

**Comment by tophsic** [comment]
I fixes this using [mgp](https://www.npmjs.com/package/mgp) but I am not sure it is necessary to include Marker library as meteor package anymore.

**Comment by aramk** [comment]
I've published at https://atmospherejs.com/aramk/google-maps-marker-label

**Comment by tophsic** [comment]
Thanks.

I am trying to use a solution closer to official google maps javascript api.
